# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'easi6driver' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  react_native_path = "../node_modules/react-native"
  pod "yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod "React", :path => react_native_path, :subspecs => [
    'CxxBridge',
  ]

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Pods for easi6driver
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'
  pod 'Firebase/Messaging'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'easi6driverTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'easi6driver-tvOS' do
#  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  # use_frameworks!
#
#  # Pods for easi6driver-tvOS
#
#  target 'easi6driver-tvOSTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#end

